openapi: 3.0.1
info:
  title: order
  description: API Definition of order
  version: 1.0.0
servers:
- url: http://localhost:8290/order
paths:
  /:
    get:
      responses:
        default:
          description: Default response
