openapi: 3.0.1
info:
  title: cms
  description: API Definition of cms
  version: 1.0.0
servers:
- url: http://localhost:8290/cms
paths:
  /login:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
  /orders:
    get:
      responses:
        default:
          description: Default response
  /new-order:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
