openapi: 3.0.1
info:
  title: customer_login
  description: API Definition of customer_login
  version: 1.0.0
servers:
- url: http://localhost:8290/customer_login
paths:
  /:
    get:
      responses:
        default:
          description: Default response
