openapi: 3.0.1
info:
  title: findmyip
  description: API Definition of findmyip
  version: 1.0.0
servers:
- url: http://localhost:8290/findmyip
paths:
  /:
    get:
      responses:
        default:
          description: Default response
