openapi: 3.0.1
info:
  title: geMyOders
  description: API Definition of geMyOders
  version: 1.0.0
servers:
- url: http://localhost:8290/my-oders
paths:
  /:
    get:
      responses:
        default:
          description: Default response
