openapi: 3.0.1
info:
  title: place_order
  description: API Definition of place_order
  version: 1.0.0
servers:
- url: http://localhost:8290/place_order
paths:
  /:
    get:
      responses:
        default:
          description: Default response
