openapi: 3.0.1
info:
  title: ROS
  description: API Definition of ROS
  version: 1.0.0
servers:
- url: http://localhost:8290/ros
paths:
  /driver/optimizeRoutes:
    get:
      parameters:
      - name: driverid
        in: query
        schema:
          type: string
      responses:
        default:
          description: Default response
