openapi: 3.0.1
info:
  title: ROS
  description: API Definition of ROS
  version: 1.0.0
servers:
- url: http://localhost:8290/ros
paths:
  /optimizeRoutes:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
  /getOrderByDriverAndStatus:
    get:
      responses:
        default:
          description: Default response
  /driver/routes/{driverId}:
    get:
      parameters:
      - name: driverId
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: Default response
