openapi: 3.0.1
info:
  title: testing
  description: API Definition of testing
  version: 1.0.0
servers:
- url: http://localhost:8290/testing
paths:
  /:
    get:
      responses:
        default:
          description: Default response
